### GET ALL
GET http://localhost:5000/bosses

### GET ONE
GET http://localhost:5000/bosses/606256cfecf5d57852bb6efc/loot

### GET ITEMS FROM ONE
GET http://localhost:5000/bosses/606256cfecf5d57852bb6efc/lootTable

### DELETE ONE
DELETE http://localhost:5000/bosses

### UPDATE ONE
PATCH http://localhost:5000/bosses
Content-Type: application/json

### CREATE ONE
POST http://localhost:5000/bosses
Content-Type: application/json

{
    "name": "Loatheb",
    "wowId": 16011,
    "image": "https://wow.zamimg.com/uploads/screenshots/normal/120824-loatheb.jpg",
    "encounterId": "605fff18c41b5b045e15fdc3"
}

# NAXX: 605fff18c41b5b045e15fdc3