### GET ALL
GET http://localhost:5000/bosses

### GET ONE
GET http://localhost:3000/bosses

### DELETE ONE
DELETE http://localhost:3000/bosses

### UPDATE ONE
PATCH http://localhost:3000/bosses
Content-Type: application/json

### CREATE ONE
POST http://localhost:5000/bosses
Content-Type: application/json

{
    "name": "Maexxna",
    "wowId": 15952,
    "image": "https://static.wikia.nocookie.net/wowwiki/images/6/6b/Maexxna.jpg",
    "encounterId": "605fff18c41b5b045e15fdc3"
}

# NAXX: 605fff18c41b5b045e15fdc3