### GET ALL
GET http://localhost:5000/items

### GET ONE
GET http://localhost:5000/items/6062b56dff6f03856f196fe8

### DELETE ONE
DELETE http://localhost:5000/items/id

### UPDATE ONE
PATCH http://localhost:5000/items/id
Content-Type: application/json

{
    "title": "Be Nice GDKP",
    "time": "2021-03-31T20:00:00.005Z",
}

### CREATE ONE
POST http://localhost:5000/items
Content-Type: application/json

{
    "name": "Necklace of Necropsy",
    "bossId": "60625818ecf5d57852bb6efd",
    "wowId": 23036
}