### GET ALL
GET http://localhost:5000/loot

### GET ONE
GET http://localhost:5000/loot/

### DELETE ONE
DELETE http://localhost:5000/loot/60642e276c08c48338999d38

### UPDATE ONE
PATCH http://localhost:5000/loot/6062bc66aa8b4e04137c740b
Content-Type: application/json

{
    "bossId": "606256cfecf5d57852bb6efc"
}

### CREATE ONE
POST http://localhost:5000/loot
Content-Type: application/json

{
    "buyer": "Wasted Time",
    "price": 2000,
    "wowId": 23000,
    "raidId": "6062b56dff6f03856f196fe8",
    "bossId": "60625818ecf5d57852bb6efd"
}