### GET ALL
GET http://localhost:5000/loot

### GET ONE
GET http://localhost:5000/loot/6070a0296c37b243c46d74a9

### DELETE ONE
DELETE http://localhost:5000/loot/60709cb5a4004141f7591cf8















### UPDATE ONE
PATCH http://localhost:5000/loot/6071f5a64a82f36a05ad9b73
Content-Type: application/json

{
    "name": "Idol of Longevity"
}













### CREATE ONE
POST http://localhost:5000/loot
Content-Type: application/json

{
    "buyer": "Earthwarden",
    "price": 400,
    "raidId": "6062b56dff6f03856f196fe8",
    "bossId": "60625513ecf5d57852bb6ef7",
    "wowId": 22365
}