### GET ALL
GET http://localhost:5000/loot

### GET ONE
GET http://localhost:5000/loot/

### DELETE ONE
DELETE http://localhost:5000/loot/60709cb5a4004141f7591cf8

### UPDATE ONE
PATCH http://localhost:5000/loot/60709c6fa4004141f7591cf6
Content-Type: application/json

{
    "bossId": "60617e233bc3b72156e3e8ad"
}

### CREATE ONE
POST http://localhost:5000/loot
Content-Type: application/json

{
    "buyer": "Butteredrice",
    "price": 6,
    "raidId": "6062b56dff6f03856f196fe8",
    "bossId": "60625223b3ecaf764a8fd162",
    "wowId": 23038
}