### GET ALL
GET http://localhost:5000/raids

### GET ONE
GET http://localhost:5000/raids/6062b56dff6f03856f196fe8

### DELETE ONE
DELETE http://localhost:5000/raids/6062b56dff6f03856f196fe8

### UPDATE ONE
PATCH http://localhost:5000/raids/id/6062b56dff6f03856f196fe8
Content-Type: application/json

{
    "slug": "1"
}

### CREATE ONE
POST http://localhost:5000/raids
Content-Type: application/json

{
    "title": "Be Nice GDKP",
    "time": "2021-03-31T20:00:00.005Z",
    "encounterId": "605fff18c41b5b045e15fdc3",
    "leaderId": "606252a8ec181277d428f2b6"
}


### GET BOSSES IN ONE
GET http://localhost:5000/raids/6062b56dff6f03856f196fe8/bosses

### GET LOOT IN ONE
GET http://localhost:5000/raids/6062b56dff6f03856f196fe8/loot

### GET LOOT FROM SPECIFIC BOSS IN RAID
GET http://localhost:5000/raids/6062b56dff6f03856f196fe8/loot/606256cfecf5d2bb6
Content-Type: application/json
