### GET ALL
GET http://localhost:5000/location

### GET ONE
GET http://localhost:5000/location/id

### DELETE ONE
DELETE http://localhost:5000/location/id

### UPDATE ONE
PATCH http://localhost:5000/location/id
Content-Type: application/json

{
    "name": "Odin Wilson"
}

### CREATE ONE
POST http://localhost:5000/location
Content-Type: application/json

{
    "name": "Cody Wilson",
    "subscribedToChannel": "Testing"
}