### GET ALL
GET http://localhost:3000/locations

### GET ONE
GET http://localhost:3000/locations/605fd091cca85ff6aa64a4f3

### DELETE ONE
DELETE http://localhost:3000/locations/605fcbadcd1d3cf4803308a8

### UPDATE ONE
PATCH http://localhost:3000/locations/605fd4ca678c1ff74d63cf31
Content-Type: application/json

{
    "name": ""
}

### CREATE ONE
POST http://localhost:3000/locations
Content-Type: application/json

{
    "name": "ONY"
}